# Jekyll Configuration for GitHub Pages
title: Sujith Nair - Data Analytics Professional
description: Personal portfolio and resume website showcasing data analytics and business intelligence expertise
url: "https://sujithnair1991.github.io"

# Theme Configuration
theme: jekyll-theme-minimal

# Site Settings
show_downloads: false

# Social Media Links
github_username: sujithnair1991
linkedin_username: sujithnairdfw
email: sujithnair1991@gmail.com

# SEO and Social
lang: en
author: Sujith Nair

# Markdown settings
markdown: kramdown
kramdown:
  input: GFM
  hard_wrap: false

# Plugin settings
plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-seo-tag

# Exclude from processing
exclude:
  - Gemfile
  - Gemfile.lock
