# Jekyll Configuration for GitHub Pages
title: Your Name - Portfolio
description: Personal portfolio and resume website hosted on GitHub Pages
url: "https://sujithnair1991.github.io"

# Theme Configuration
theme: jekyll-theme-minimal

# Site Settings
show_downloads: false

# Social Media Links
github_username: sujithnair1991
linkedin_username: yourprofile
email: your.email@example.com

# SEO and Social
lang: en
author: Your Name

# Markdown settings
markdown: kramdown
kramdown:
  input: GFM
  hard_wrap: false

# Plugin settings
plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-seo-tag

# Exclude from processing
exclude:
  - Gemfile
  - Gemfile.lock
  - README.md
